plans = Plan.create([{platform: 'Facebook', 
                    price: 3000.00, 
                    limit_daily: 400,
                    limit_monthly: 10000,
                    cost: 0.50,
                    promo: 'Promoção Facebook'},
                    {platform: 'Whatsapp', 
                    price: 4000.00, 
                    limit_daily: 800,
                    limit_monthly: 18000,
                    cost: 0.80,
                    promo: 'Promoção Whatsapp'}])